<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-11-16T17:46:16 IST" name="Suite" finished-at="2022-11-16T17:46:34 IST" duration-ms="18188">
    <groups>
      <group name="testerror">
        <method signature="ErrorValidations.validation()[pri:0, instance:usingmaven.ErrorValidations@64c63c79]" name="validation" class="usingmaven.ErrorValidations"/>
      </group> <!-- testerror -->
    </groups>
    <test started-at="2022-11-16T17:46:16 IST" name="NegativeTest" finished-at="2022-11-16T17:46:34 IST" duration-ms="18188">
      <class name="usingmaven.ErrorValidations">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:usingmaven.ErrorValidations@64c63c79]" started-at="2022-11-16T17:46:16 IST" name="launchApplication" finished-at="2022-11-16T17:46:17 IST" duration-ms="1470" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="productValidation()[pri:0, instance:usingmaven.ErrorValidations@64c63c79]" started-at="2022-11-16T17:46:17 IST" name="productValidation" finished-at="2022-11-16T17:46:31 IST" duration-ms="13476" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- productValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:usingmaven.ErrorValidations@64c63c79]" started-at="2022-11-16T17:46:31 IST" name="tearDown" finished-at="2022-11-16T17:46:31 IST" duration-ms="55" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:usingmaven.ErrorValidations@64c63c79]" started-at="2022-11-16T17:46:31 IST" name="launchApplication" finished-at="2022-11-16T17:46:33 IST" duration-ms="1878" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="validation()[pri:0, instance:usingmaven.ErrorValidations@64c63c79]" started-at="2022-11-16T17:46:33 IST" name="validation" finished-at="2022-11-16T17:46:34 IST" duration-ms="849" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or password.] but found [Incorrect email password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Incorrect email password.]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at usingmaven.ErrorValidations.validation(ErrorValidations.java:23)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:usingmaven.ErrorValidations@64c63c79]" started-at="2022-11-16T17:46:34 IST" name="tearDown" finished-at="2022-11-16T17:46:34 IST" duration-ms="54" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- usingmaven.ErrorValidations -->
    </test> <!-- NegativeTest -->
  </suite> <!-- Suite -->
</testng-results>
